# coding: utf-8

"""
    Scout9 API

    APIs for managing Scout9 users and conversations  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.list_customers_response import ListCustomersResponse
from openapi_client import configuration


class TestListCustomersResponse(unittest.TestCase):
    """ListCustomersResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
