# coding: utf-8

"""
    Scout9 API

    APIs for managing Scout9 users and conversations  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from scout9 import schemas  # noqa: F401


class ListCustomersResponse(
    schemas.ListSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:

        @staticmethod
        def items() -> typing.Type['Customer']:
            return Customer

    def __new__(
        cls,
        _arg: typing.Union[typing.Tuple['Customer'], typing.List['Customer']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ListCustomersResponse':
        return super().__new__(
            cls,
            _arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'Customer':
        return super().__getitem__(i)

from scout9.model.customer import Customer
