# coding: utf-8

"""
    Scout9 API

    APIs for managing Scout9 users and conversations  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_customer.post import CreateCustomer
from openapi_client.paths.v1_customers.post import CreateCustomers
from openapi_client.paths.v1_customer.delete import DeleteCustomer
from openapi_client.paths.v1_customers.delete import DeleteCustomers
from openapi_client.paths.v1_customer.get import GetCustomer
from openapi_client.paths.v1_customers.get import GetCustomers
from openapi_client.paths.v1_customer.put import UpdateCustomer
from openapi_client.paths.v1_customers.put import UpdateCustomers


class Scout9Api(
    CreateCustomer,
    CreateCustomers,
    DeleteCustomer,
    DeleteCustomers,
    GetCustomer,
    GetCustomers,
    UpdateCustomer,
    UpdateCustomers,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
